unity_launcher_sources += files(
  'unity-app-tile.c',
  'unity-launcher-app-tile.c',
  'unity-dash-app-tile.c',
  'unity-search-result-row.c',
  'unity-hide.c',
  'unity-launcher-app-strip.c',
  'unity-launcher-dash-button.c',
  'unity-pinned-apps-reorder.c',
  'unity-dismiss.c',
  'unity-pinned-apps.c',
  'unity-desktop-actions.c',
)
